85 highlight video when speaking
montevideo-tech/hybrid-meetup-platform pull request #112
Opened 2023-02-28 17:36 UTC by gerardoquinckequalabs

Added event listeners for participants when they join: StartedSpeaking and StoppedSpeaking.
Highlight the video box with a colored border when participant is speaking.
The video box now have rounded corners.

2023-02-28 17:59 UTC, hernanr99 approved these changes

2023-02-28 20:38 UTC, ghbogarin reviewed
@gerardoquinckequalabs everything seems to be working fine!

Small detail: I get a white line at the bottom of the video container. That was already there, but it becomes visible now that we have a border in the video container. 
I suggest adding `display: 'block'` in the style of the video tag (line 52). That seems to solve that issue.

2023-03-01 17:49 UTC, clararfe requested changes
Hi Gera, there is an issue when you enter a room where there is already a participant. In this case the participantJoined event is not triggered so we don't listen to the startSpeaking event. We should add this listener on the subscribeToRemoteStreams as well.

2023-03-21 18:08 UTC, JonaQuaLabs approved these changes

2023-03-21 18:26 UTC, Unnil commented on package-lock.json
Should this file be merged?

2023-03-21 18:28 UTC, fpyoung commented on package-lock.json
you are right! we should remove this file from the PR.

2023-03-21 18:35 UTC, fyoungqualabs commented on package-lock.json
done!

2023-03-21 18:43 UTC, Unnil approved these changes

2023-03-21 18:43 UTC, Unnil commented on frontend/src/views/Room.jsx
> +        });
Can we encapsulate all of this in a function? I see that is duplicated when we join and then when a participant joins.

2023-03-22 17:38 UTC, fpyoung commented on frontend/src/views/Room.jsx
> +        });
fixed!

2023-03-22 17:38 UTC, merged