backend file structure
montevideo-tech/hybrid-meetup-platform pull request #50
Opened 2023-02-09 06:44 UTC by FelipeDeMoura

### Summary:
- Placeholder for the Supabase Edge functions 
- Backend file structure

### What problem does it solve?
- Mainly to decouple presentation layer (frontend) from business logic (backend)
- Any integration with vendor could be implemented on the backend or edge functions

```
.
└── src
    ├── lib
    │   ├── api
    │   └── vendor
    ├── local
    └── supabase
        ├── functions
        │   ├── sign-in
        │   ├── sign-in-with-google
        │   ├── sign-out
        │   └── sign-up
        └── migrations
```

### What areas of the site does it impact?
- Place where any future function calls or backend services will reside.

## Checklist
- [ ] You have added unit tests
- [ ] No error nor warning in the console or builds
- [ ] I joined a screenshot of developed feature (if applicable)
- [ ] Documentation (if applicable)

## Other Notes (Supabase)

- All APIs are auto-created from Database tables. After you have added tables or functions to your database, you can use the APIs provided.

- For use-cases which require low-latency we recommend Edge Functions, which are globally-distributed and can be written in TypeScript. (Supabase Edge functions are written in typescript run via Deno)

- We recommend developing “fat functions”. This means that you should develop few large functions, rather than many small functions. 

[upload the screenshot here]

2023-02-09 18:23 UTC, hernanr99 approved these changes

2023-02-10 13:37 UTC, mpollingerQualabs requested changes

2023-02-10 13:37 UTC, mpollingerQualabs commented on backend/.vscode/settings.json
> +}
Need to add this `.vscode` directory to .gitignore

2023-02-10 13:45 UTC, hernanr99 approved these changes

2023-02-10 13:47 UTC, mpollingerQualabs approved these changes

2023-02-10 13:52 UTC, clararfe approved these changes

2023-02-10 13:53 UTC, merged